# Generated by Django 4.0.1 on 2022-04-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
